### ISSUE TITLE
Error GattCallback 133 when connected device

### ISSUE THREAD

**Issue by nicodwi** [didourebai/BLEPluginDemo#1]
Hello,

I always got this error when i'm trying to connect the device since the first time.
ALready try stop scan before connect and use timeout also won't solved this problem.
Can you please help me how to solved this error?

Thx

**Comment by didourebai** [comment]
Could you attach your error to be able to help you and update this version if needed?

**Comment by nicodwi** [comment]
Really sorry for the trouble, but how to get error log for this one?
I'm newbie in xamarin and ble.

Thx

**Comment by didourebai** [comment]
Please, could you tell me more about the environment? 
Are you trying Android version or iOS version? Are you using an emulator or a Device?

**Comment by nicodwi** [comment]
I'm using this one (2 separated device)

Version of the Plugin: 1.3.0
Platform: Android 5.1.1 & Marshmallow
Device: Xiaomi Redmi 3 & LG G3

**Comment by nicodwi** [comment]
Didourebai, any solution for this issue?

**Comment by didourebai** [comment]
The problem is related to the Platform, I'm trying to adapt it, I'm using Android 7. 0. (Samsung).
I will fix that as soon as possible.

**Comment by nicodwi** [comment]
Thx didourebai.
I'm really need that fix.

**Comment by didourebai** [comment]
![dw](https://user-images.githubusercontent.com/11868839/35266024-3893d0de-0022-11e8-95bb-d65d4882850f.JPG)
Hello,
Could you try this source: 
https://code.msdn.microsoft.com/Quest-ce-que-Bluetooth-LE-43bf5116
![1](https://user-images.githubusercontent.com/11868839/35265998-25e3776e-0022-11e8-8ffb-5132db870f9e.JPG)
![2](https://user-images.githubusercontent.com/11868839/35265999-25fcefb4-0022-11e8-8660-4e2cf7bcbc33.JPG)
![3](https://user-images.githubusercontent.com/11868839/35266000-261885da-0022-11e8-9312-f00ca4d80c3e.JPG)

**Comment by wogh1759** [comment]
can i get this source?
i can not see scanlist at my phone.

https://code.msdn.microsoft.com/Quest-ce-que-Bluetooth-LE-43bf5116
link is not open to me

**Comment by emrealp35** [comment]
Hello, Thanks for example.
I get the error when I try to use Get Characteristic. I couldn't understand: /
For example I can easily get a get service. I can read Device Id and Device name. But I can't read anything with the charasteristic get. I'm using the bluetooth HM-10.
 I want to send a simple character. For example Send Character ("Hello").I'm so confused ?
![2019-04-11_22-46-43](https://user-images.githubusercontent.com/31658494/55988220-f7ea4800-5cab-11e9-9bbc-9e76c7018b7e.png)
![2019-04-11_22-47-41](https://user-images.githubusercontent.com/31658494/55988224-fc166580-5cab-11e9-83be-e425ecf4efe0.png)

**Comment by mkhambaty** [comment]
I got the same problem as @emrealp35. Is there a solution for this? Thank you

**Comment by fox-dda** [comment]
> I got the same problem as @emrealp35. Is there a solution for this? Thank you
Try this code to connect. It works for me
``` C#
Device.BeginInvokeOnMainThread(async () =>
            {

                bool isTryGuid = false;
                await _adapter.StopScanningForDevicesAsync();
                try
                {
                    await _adapter.ConnectToDeviceAsync(_device);
                }
                catch (Exception e)
                {
                    isTryGuid = true;
                    System.Diagnostics.Debug.WriteLine(e.Message);
                }
                if (isTryGuid)
                {
                    try
                    {
                        await _adapter.ConnectToKnownDeviceAsync(_device.Id);
                    }
                    catch (Exception e)
                    {
                        System.Diagnostics.Debug.WriteLine(e.Message);
                    }
                }
            });
```

**Comment by emrealp35** [comment]
Thank you too much . I will try

Dmitry Domaskin <notifications@github.com>, 5 Ara 2019 Per, 09:25 tarihinde
şunu yazdı:

**Comment by akad90** [comment]
Hi everyone,

Thanks for your comments and thanks didourebai for your huge time and effort. 
I am trying to get this going and have the following problems:
- list of scanned devices displays as a blank list (a few blank lines are added) when [SCAN] selected.
- any function ie [GET CHARACTERISTICS] returns the same error as mentioned by others (Object ref..)

VS2019 - tested on an Android device - Android 7.1 & 9.
Has anyone found any solutions yet? 
Thanks in advance.
